[db]
dsn = "user=postgres password=postgres dbname=flow port=5432 host=localhost sslmode=disable"

[http]
addr = ":8080"
domain = ""
hash-key = "30d7d3557b6d730c3e3954999c58edd8"
block-key = "a52a0a3c2704d563d6ffbd281ea39809"
